name: Build and deploy java app

on:
    push:
        branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SetUp JDK
      uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build with maven
      run: mvn clean package

    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{secrets.DOCKER_USERNAME}}/java-k8s-app:latest .
        docker push ${{secrets.DOCKER_USERNAME}}/java-k8s-app:latest

    - name: SetUp Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Prepare kubeconfig
      run: |
        echo "ðŸ”§ Creating .kube directory..."
        mkdir -p $HOME/.kube

        echo "ðŸ“¦ Decoding kubeconfig..."
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

        echo "ðŸ” Securing permissions..."
        chmod 600 $HOME/.kube/config

        echo "âœ… kubeconfig ready at $HOME/.kube/config"

    - name: Verify cluster access
      run: kubectl get nodes --kubeconfig=$HOME/.kube/config

    - name: Configure Kubernetes
      run: |
        mkdir -p $HOME/.kube
        echo "${{secrets.KUBE_CONFIG}}" | base64 --decode > $HOME/.kube/config
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml


        
            
